id: IFA9FBFAF
ocr_import_info:
  timestamp: '2023-09-29T10:46:50.948987+00:00'
  batch_id: batch-33ca
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-29 12:59:11.142460+00:00
last_modified: 2023-09-29 12:59:11.142467+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3PD887
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3PD887
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསང་འདུས་སྐོར་དཔེ་རྙིང་དཔེ་དཀོན།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9094544185068555
  ocr_word_median_confidence_index: 0.96882565
bases:
  I3PD1192:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3PD1192
      total_pages: 500
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3PD1192.txt
    statistics:
      ocr_word_median_confidence_index: 0.9811005
      ocr_word_mean_confidence_index: 0.9207344996469008
  I3PD1193:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3PD1193
      total_pages: 492
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3PD1193.txt
    statistics:
      ocr_word_median_confidence_index: 0.9570117
      ocr_word_mean_confidence_index: 0.9006881505392175
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
